### ISSUE TITLE
AttributeError for `on_message_edit()`

### ISSUE THREAD

**Issue by Mister-SOSA** [Mister-SOSA/SOSABot2#3]
```2023-11-06 23:05:29,701:ERROR - Ignoring exception in on_message_edit
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.11.6/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/SOSABot2/Discord/cogs/listeners/on_message_edit.py", line 13, in on_message_edit
    if before.msg.author.bot:
       ^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'msg'```

**Comment by Mister-SOSA** [comment]
resolved in #3fa76cf
